name: Linting

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-first.txt
          pip install -r requirements-dev.txt
      - name: isort
        run: isort --recursive --diff
      - name: Black
        run: black --check .
